### ISSUE TITLE
some errors appear while starting

### ISSUE THREAD

**Issue by 694982827** [wjxzju/Face-Recognition-Web-demo#1]
root@nova-5a2851fc-6f2b-47e0-bc2c-067b7eee1ca8:/usr/local/web/webapp# python app.py 
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 6:15: Message type "caffe.LayerParameter" has no field named "input_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1028 05:36:37.538421  2453 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /usr/local/web/recognition/proto/LightenedCNN_B_deploy_ugrade.prototxt
**\* Check failure stack trace: ***
Aborted
root@nova-5a2851fc-6f2b-47e0-bc2c-067b7eee1ca8:/usr/local/web/webapp# 
why?

**Comment by wjxzju** [comment]
Sorry for late, I think you should update your caffe framework, you can see this issue  [Data Layer unknown layer type](https://github.com/BVLC/caffe/issues/3846)
